# This file was generated by GoReleaser. DO NOT EDIT.
cask "tedis" do
  postflight do
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", staged_path.to_s
  end

  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "ea7668e5bfdce03a3cc1c40eb5c156df13aae39d857e82779fbc319e92e12efc"
      url "https://github.com/itbaby/tedis/releases/download/v#{version}/tedis_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4fd128f44a579c53b23397c5f953d9efdec40b2560678bcdf10a4b7e688b5b46"
      url "https://github.com/itbaby/tedis/releases/download/v#{version}/tedis_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3c42b576328b46cd39bcbaa5010d63fb92a30113e6cbaa9c2af2c8b707bb149d"
      url "https://github.com/itbaby/tedis/releases/download/v#{version}/tedis_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b38248023ae594e010915c717f131ec853679a5a58c168e36e192d1285690ba9"
      url "https://github.com/itbaby/tedis/releases/download/v#{version}/tedis_linux_amd64.tar.gz"
    end
  end

  name "tedis"
  desc "Keyboard-driven Redis TUI: tree browser, live value inspector, query console"
  homepage "https://github.com/itbaby/tedis"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tedis"

  # No zap stanza required
end
