# This file was generated by GoReleaser. DO NOT EDIT.
cask "tedis" do
  postflight do
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", staged_path.to_s
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "e080705652af59caa2826d9f9cdcf4be21233eed6814bfd35850f3c13d65427c"
      url "https://github.com/itbaby/tedis/releases/download/v#{version}/tedis_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "16ad6b14d94c5944566b4b844e266ba0f968346ce8833f09b07592d0c2b73392"
      url "https://github.com/itbaby/tedis/releases/download/v#{version}/tedis_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0ad7d77364e7572b3bd354fd6389f63adf25b45297dc8674562cfdad60af5221"
      url "https://github.com/itbaby/tedis/releases/download/v#{version}/tedis_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e202922a43f7628edaa5c773a41cd8a4d2f2e13bd4ee4060806a14157266d9ed"
      url "https://github.com/itbaby/tedis/releases/download/v#{version}/tedis_linux_amd64.tar.gz"
    end
  end

  name "tedis"
  desc "Keyboard-driven Redis TUI: tree browser, live value inspector, query console"
  homepage "https://github.com/itbaby/tedis"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tedis"

  # No zap stanza required
end
